FROM ubuntu:16.10

RUN \
apt-get update && \

# modsecurity
apt-get install -y git &&\
apt-get install -y autoconf &&\
apt-get install -y libtool &&\
apt-get install -y apache2-dev &&\
apt-get install -y libpcre3 &&\
apt-get install -y libpcre3-dev &&\
apt-get install -y libxml2-dev &&\

cd /tmp &&\
git clone https://github.com/SpiderLabs/ModSecurity.git mod_security &&\
cd /tmp/mod_security &&\
./autogen.sh &&\
./configure --enable-standalone-module &&\
make &&\


# nginx
apt-get install -y wget && \
apt-get install -y zlib1g-dev && \
apt-get install -y libssl-dev && \
cd /tmp && \
wget http://nginx.org/download/nginx-1.12.0.tar.gz && \
tar xvzf nginx-1.12.0.tar.gz && \
cd  /tmp/nginx-1.12.0 && \
./configure --add-module=/tmp/mod_security/nginx/modsecurity --with-http_ssl_module --with-http_stub_status_module && \
make install && \


#mrtgひとまず保留
#apt-get install -y mrtg && \


mkdir -p /usr/local/nginx/conf/sites-enabled &&\
mkdir -p /var/cache/nginx/cache &&\
mkdir -p /var/cache/nginx/cache/temp &&\
ln -s /usr/local/nginx/sbin/nginx /usr/bin/nginx &&\
echo "export PATH=$PATH:/usr/local/nginx/sbin" >> ~/.bashrc &&\



# time settings
apt-get install -y ntp &&\
cp /etc/localtime /etc/localtime.utc &&\
ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime &&\
echo "server ntp.nict.jp" >> /etc/ntp.conf &&\
echo "server ntp.nict.jp" >> /etc/ntp.conf &&\
echo "server ntp.nict.jp" >> /etc/ntp.conf


# Expose orts.
EXPOSE 80
EXPOSE 443

#VOLUME ["log", "conf.d", "html"]

# Define working directory.
WORKDIR /usr/local/nginx


# Define default command.
# CMD ["nginx"]


