version: '2'
services:
 nginx:
  build: .
  image: im_varnish_nginx
  container_name: "varnish_nginx"
  working_dir: "/etc/nginx"
  volumes:
    - ./conf/default:/etc/nginx/sites-available/default
    - ./conf/nginx.conf:/etc/nginx/nginx.conf
  # volumes:
  #   - /Users/issei/prog/dockerfileTrain/log/nginx:/usr/local/nginx/logs
  #   - /Users/issei/prog/dockerfileTrain/html:/var/www/html
  #   - /Users/issei/prog/dockerfileTrain/conf/nginx.conf:/usr/local/nginx/conf/nginx.conf
  #   - /Users/issei/prog/dockerfileTrain/conf/modsecurity.conf:/usr/local/nginx/conf/modsecurity.conf
    # - /Users/issei/prog/dockerfileTrain/conf/default:/usr/local/nginx/conf/sites-enabled/default
  command: bash
  ports:
    - "8089:80"

  tty : true
